# Generated by Django 5.2.13 on 2026-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
