# Generated by Django 5.2.13 on 2026-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='syllabus_presets/')),
                ('csv_link', models.CharField(blank=True, help_text='Direct URL to CSV file if hosted externally', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Syllabus Preset',
                'verbose_name_plural': 'Syllabus Presets',
                'ordering': ['-created_at'],
            },
        ),
    ]
