# Generated by Django 5.2.13 on 2026-07-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_habitentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_good_habit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_good_habit',
            field=models.BooleanField(default=False),
        ),
    ]
